### PR TITLE
Feature/fix location listener crashes

### PR DESCRIPTION
**Pull request by xni06**
Fix for #40 and #33 (and also an edge case for #24 that has already been closed)

### CODE REVIEW

**Comment by xni06** [comment]
This PR requires some more work

**Comment by igaurab** [comment]
@xni06 currently I am not able to test it, can you please confirm if I can accept the PR?

**Comment by xni06** [comment]
I'll reply this weekend once I'm back from holiday.

**Comment by xni06** [comment]
- Upon touching the _location_ button, there was an error log - fixed
- Upon touching the _location_ button then navigating _back_, an error would be logged continuously - fixed

These were confirmed during regression testing in both _dev_ and _release_ mode.

In addition, this PR has been positively commented on in https://github.com/igaurab/user_location_plugin/issues/37#issuecomment-598436110

**Review by konishon — APPROVED** [review]

**Pull request merged**
